class SummedRadixTree:
    def __init__(self, items: Optional[Dict[int, int]] = None) -> None: ...
    def contains(self, element: int) -> bool: ...
    def __contains__(self, element: int) -> bool: ...
    
    def add(self, element: int, value: int) -> 'SummedRadixTree': ...
    def union(self, other: 'SummedRadixTree') -> 'SummedRadixTree': ...
    @property
    def total(self) -> int: ...
    def __or__(self, other: 'SummedRadixTree') -> 'SummedRadixTree': ...
    def __add__(self, other: Tuple[int, int]) -> 'SummedRadixTree': ...
    def __getitem__(self, element: int) -> int: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> Iterator[Tuple[int, int]]: ...
    def __len__(self) -> int: ...

    